version: "3.7"
services:
  ChatGPTAPI:
    image: chatgpt:latest
    container_name: ChatGPTAPI
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1024m"
    ports:
      - "8888:8888"
    environment:
      REPO_URL_GITSCRIPTS: https://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@github.com/hyyds/ChatGPTAPI.git
      REPO_BRANCH: main
      PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium-browser'
